SET SERVEROUTPUT ON
/*DECLARE
    V_CONTADOR NUMBER(2) := 1;
BEGIN
LOOP
    DBMS_OUTPUT.PUT_LINE(V_CONTADOR);
    V_CONTADOR := V_CONTADOR + 1;
    EXIT WHEN V_CONTADOR > 20;
END LOOP;
END;*/

/*DECLARE
    V_CONTADOR NUMBER(2) := 1;
BEGIN
WHILE V_CONTADOR <= 20 LOOP
    DBMS_OUTPUT.PUT_LINE(V_CONTADOR);
    V_CONTADOR := V_CONTADOR + 1;
END LOOP;
END;*/

/*BEGIN
FOR V_CONTADOR IN 1..20 LOOP
    DBMS_OUTPUT.PUT_LINE(V_CONTADOR);
END LOOP;
END;*/

/*BEGIN
FOR V_CONTADOR IN REVERSE 1..20 LOOP
    DBMS_OUTPUT.PUT_LINE(V_CONTADOR);
END LOOP;
END;*/

/*DECLARE
    TABUADA NUMBER := 150;
    RESULT NUMBER;
BEGIN
FOR V_MULTIPLICADO IN 1..10 LOOP
    RESULT := TABUADA * V_MULTIPLICADO;
    DBMS_OUTPUT.PUT_LINE(RESULT);
END LOOP;
END;*/

/*DECLARE
    PARES NUMBER := 0;
    IMPARES NUMBER := 0;
BEGIN
    FOR V_NUMERO IN 1..21 LOOP
        IF MOD(V_NUMERO, 2) = 0 THEN
            PARES := PARES + 1;
        ELSE
            IMPARES := IMPARES + 1;
        END IF;
    END LOOP;
    DBMS_OUTPUT.PUT_LINE('PARES: ' || PARES);
    DBMS_OUTPUT.PUT_LINE('IMPARES: ' || IMPARES);
END;*/

/*DECLARE
    PARES NUMBER := 0;
    IMPARES NUMBER := 0;
    DIVISOR NUMBER := 0;
    RESULTADO NUMBER;
BEGIN
    FOR V_NUMERO IN 1..21 LOOP
        IF MOD(V_NUMERO, 2) = 0 THEN
            PARES := PARES + V_NUMERO;
            DIVISOR := DIVISOR + 1;
        ELSE
            IMPARES := IMPARES + V_NUMERO;
        END IF;
    END LOOP;
    RESULTADO := PARES / DIVISOR;
    
    DBMS_OUTPUT.PUT_LINE('MÉDIA PARES: ' || RESULTADO);
    DBMS_OUTPUT.PUT_LINE('SOMA IMPARES: ' || IMPARES);
END;*/

