/*SELECT *
FROM EMPLOYEES E
WHERE E.DEPARTMENT_ID = (SELECT DEPARTMENT_ID
    FROM DEPARTMENTS D
    WHERE UPPER(D.DEPARTMENT_NAME) = 'MARKETING')
ORDER BY E.EMPLOYEE_ID;

SELECT
    E.EMPLOYEE_ID,
    E.FIRST_NAME || ' ' || E.LAST_NAME AS NOME_FUNCIONARIO,
    E.MANAGER_ID,
    (SELECT M.FIRST_NAME || ' ' || M.LAST_NAME
    FROM EMPLOYEES M
    WHERE E.MANAGER_ID = M.EMPLOYEE_ID) AS NOME_GERENTE
FROM EMPLOYEES E
WHERE ( E.DEPARTMENT_ID, E.FIRST_NAME ) IN
    (SELECT M2.DEPARTMENT_ID,
    M2.FIRST_NAME
    FROM EMPLOYEES M2
    WHERE E.MANAGER_ID = M2.EMPLOYEE_ID)
ORDER BY E.EMPLOYEE_ID;

DROP TABLE PROMOCOES CASCADE CONSTRAINTS;

CREATE TABLE  PROMOCOES (
PROMOTION_EMPLOYEE_ID NUMBER(6,0)
, EMPLOYEE_ID NUMBER(6,0)
, DT_PROMOTION DATE
);

INSERT INTO PROMOCOES (EMPLOYEE_ID, DT_PROMOTION)
    SELECT
        E.EMPLOYEE_ID,
        SYSDATE
    FROM EMPLOYEES E
    JOIN JOB_HISTORY J ON E.EMPLOYEE_ID = J.EMPLOYEE_ID
    WHERE E.JOB_ID = J.JOB_ID
    AND MONTHS_BETWEEN(SYSDATE, J.END_DATE) > 12
    ORDER BY E.EMPLOYEE_ID;
    
SELECT  SUBQUERY.FIRST_NAME,
        SUBQUERY.JOB_ID,
        SUBQUERY.SALARY,
        SUBQUERY.MEDIA_SALARIO_CARGO
FROM (SELECT E.FIRST_NAME,
        E.JOB_ID,
        E.SALARY,
        (SELECT AVG(E2.SALARY)
        FROM EMPLOYEES E2
        WHERE E.JOB_ID = E2.JOB_ID
        GROUP BY JOB_ID) MEDIA_SALARIO_CARGO
        FROM EMPLOYEES E) SUBQUERY
WHERE SUBQUERY.SALARY > SUBQUERY.MEDIA_SALARIO_CARGO;

CREATE TABLE PEDIDO_NOVOS AS SELECT * FROM PEDIDO;
ALTER TABLE PEDIDO_NOVOS ADD STATYS VARCHAR2(30);
SELECT * FROM PEDIDO_NOVOS;
*/

/*CREATE OR REPLACE TRIGGER trg_pedido
    BEFORE INSERT ON PEDIDO_NOVOS
    FOR EACH ROW
BEGIN
    -- ATUALIZA O STATUS DO PEDIDO PARA "NOVO" APÓS A INSERÇÃO
    IF :NEW.STATYS IS NULL THEN
        :NEW.STATYS := 'Novo Pedido';
    END IF;
END;

INSERT INTO pedido_novos (
    cod_pedido,
    cod_pedido_relacionado,
    cod_cliente,
    cod_usuario,
    cod_vendedor,
    dat_pedido,
    dat_cancelamento,
    dat_entrega,
    val_total_pedido,
    val_desconto,
    seq_endereco_cliente,
    statys
) VALUES (
    1123151,
    null,
    62345245,
    1,
    2,
    SYSDATE,
    SYSDATE,
    SYSDATE,
    235.17,
    20.15,
    NULL,
    NULL
);



CREATE TABLE TB_AUDITORIA
(
    ID  NUMBER  GENERATED ALWAYS AS IDENTITY,
    TABELA VARCHAR2(30),
    OPERACAO VARCHAR2(30),
    DATA DATE,
    USUARIO VARCHAR2(30)
);
*/

CREATE OR REPLACE TRIGGER trg_auditoria
    AFTER INSERT OR UPDATE OR DELETE ON PEDIDO_NOVOS
    FOR EACH ROW
DECLARE
    OPERACAO        VARCHAR2(30);
    NOME_USUARIO    VARCHAR2(100);
BEGIN
    -- DETERMINA A OPERAÇÃO REALIZADA (INSERT, UPDATE OU DELETE)
    IF INSERTING THEN
        OPERACAO := 'INSERT';
    ELSIF UPDATING THEN
        OPERACAO := 'UPDATE';
    ELSIF DELETING THEN
        OPERACAO := 'DELETE';
    END IF;

    -- OBTEM O NOME DO USUARIO DA SESSÃO ATUAL
    NOME_USUARIO := SYS_CONTEXT('USERENV', 'SESSION_USER');
    
    -- REGISTRA A AUDITORIA NA TABELA DE AUDITORIA
    INSERT INTO TB_AUDITORIA
        (TABELA, OPERACAO, DATA, USUARIO)
    VALUES
        ('PEDIDO_NOVOS', OPERACAO, SYSDATE, NOME_USUARIO);
END;



















    