-- PAIS
CREATE TABLE A001_PAIS (
ID_PAIS NUMBER GENERATED ALWAYS AS IDENTITY,
NOME VARCHAR2(30),
PRIMARY KEY (ID_PAIS));
-- ESTADO
CREATE TABLE A001_ESTADO (
ID_ESTADO NUMBER GENERATED ALWAYS AS IDENTITY,
NOME VARCHAR2(30),
ID_PAIS NUMBER,
PRIMARY KEY(ID_ESTADO));

ALTER TABLE A001_ESTADO ADD CONSTRAINT FK_ESTADO FOREIGN KEY (ID_PAIS) REFERENCES A001_PAIS;
-- CIDADE
CREATE TABLE A001_CIDADE (
ID_CIDADE NUMBER GENERATED ALWAYS AS IDENTITY,
NOME VARCHAR2(30),
ID_ESTADO NUMBER,
PRIMARY KEY(ID_CIDADE));

ALTER TABLE A001_CIDADE ADD CONSTRAINT FK_CIDADE FOREIGN KEY (ID_ESTADO) REFERENCES A001_ESTADO;
-- BAIRRO
CREATE TABLE A001_BAIRRO (
ID_BAIRRO NUMBER GENERATED ALWAYS AS IDENTITY,
NOME VARCHAR2(30),
ID_CIDADE NUMBER,
PRIMARY KEY(ID_BAIRRO));

ALTER TABLE A001_BAIRRO ADD CONSTRAINT FK_BAIRRO FOREIGN KEY (ID_CIDADE) REFERENCES A001_CIDADE;
-- ENDEREÇO_CLIENTE
CREATE TABLE A001_ENDERECO_CLIENTE (
ID_ENDERECO NUMBER GENERATED ALWAYS AS IDENTITY,
CEP VARCHAR2(30),
ID_BAIRRO NUMBER,
REFERENCIA VARCHAR2(30),
PRIMARY KEY(ID_ENDERECO));

ALTER TABLE A001_ENDERECO_CLIENTE ADD CONSTRAINT FK_ENDERECO FOREIGN KEY (ID_BAIRRO) REFERENCES A001_BAIRRO;
