CREATE OR REPLACE PACKAGE PKG_EXERCICIO1 AS
    PROCEDURE PRC_INSERE_NOVO_PAIS(P_COD_PAIS   PAIS.COD_PAIS%TYPE, P_NOM_PAIS  PAIS.NOM_PAIS%TYPE);
    FUNCTION FUN_VALIDA_NOME66(P_NOME IN VARCHAR2) RETURN BOOLEAN;
    PROCEDURE PRC_INSERE_NOVO_ESTADO(P_COD_ESTADO   ESTADO.COD_ESTADO%TYPE, P_NOME_ESTADO   ESTADO.NOM_ESTADO%TYPE, P_COD_PAIS  ESTADO.COD_PAIS%TYPE);
END PKG_EXERCICIO1;

/

CREATE OR REPLACE PACKAGE BODY PKG_EXERCICIO1 AS
    FUNCTION FUN_VALIDA_NOME66(P_NOME IN VARCHAR2) RETURN BOOLEAN IS
    BEGIN
        IF NOT REGEXP_LIKE(P_NOME, '[0-9]') THEN
            RETURN TRUE;
        ELSE
            RETURN FALSE;
        END IF;
    
    PROCEDURE PRC_
END PKG_EXERCICIO1;