--EXERCICIO 6
CREATE OR REPLACE PROCEDURE ListarMovimentosEstoqueProduto(CODIGO_PRODUTO IN NUMBER)
IS
    DATA_MOVIMENTACAO DATE;
    QTD_MOVIMENTACAO INTEGER;
    DESCRICAO_TIPO_MOVIMENTACAO TIPO_MOVIMENTO_ESTOQUE.DES_TIPO_MOVIMENTO_ESTOQUE%TYPE;
    ESTOQUE_EXCEPTION EXCEPTION;
BEGIN

    SELECT M.DAT_MOVIMENTO_ESTOQUE, M.QTD_MOVIMENTACAO_ESTOQUE, T.DES_TIPO_MOVIMENTO_ESTOQUE
    INTO DATA_MOVIMENTACAO, QTD_MOVIMENTACAO, DESCRICAO_TIPO_MOVIMENTACAO
    FROM PRODUTO P 
    INNER JOIN MOVIMENTO_ESTOQUE M ON (P.COD_PRODUTO = M.COD_PRODUTO)
    INNER JOIN TIPO_MOVIMENTO_ESTOQUE T ON (M.COD_TIPO_MOVIMENTO_ESTOQUE = T.COD_TIPO_MOVIMENTO_ESTOQUE)
    WHERE P.COD_PRODUTO = CODIGO_PRODUTO;
    
    DBMS_OUTPUT.PUT_LINE('Data movimentacao do produto: ' || DATA_MOVIMENTACAO);
    DBMS_OUTPUT.PUT_LINE('Quantidade movimentacao estoque: ' || QTD_MOVIMENTACAO);
    DBMS_OUTPUT.PUT_LINE('Descricao tipo movimentacao estoque: ' || DESCRICAO_TIPO_MOVIMENTACAO);
    
    IF SQL%NOTFOUND THEN
        RAISE ESTOQUE_EXCEPTION;
    END IF;

EXCEPTION
    WHEN ESTOQUE_EXCEPTION THEN
        RAISE_APPLICATION_ERROR(-20001, 'N o h  produtos com este codigo.');
END;