-- EXERCICIO 5
CREATE OR REPLACE PROCEDURE ListarItensPedido(CODIGO_PEDIDO IN NUMBER)
IS
    CODIGO_ITEM NUMBER;
    NOME_PRODUTO PRODUTO.NOM_PRODUTO%TYPE;
    QTD_ITEM NUMBER;
    ITEM_EXCEPTION EXCEPTION;
BEGIN

    SELECT I.COD_ITEM_PEDIDO, P.NOM_PRODUTO, I.QTD_ITEM
    INTO CODIGO_ITEM, NOME_PRODUTO, QTD_ITEM
    FROM PEDIDO P 
    INNER JOIN ITEM_PEDIDO I ON(P.COD_PEDIDO = I.COD_PEDIDO)
    INNER JOIN PRODUTO P ON (I.COD_PRODUTO = P.COD_PRODUTO)
    WHERE P.COD_PEDIDO = CODIGO_PEDIDO;
    
    DBMS_OUTPUT.PUT_LINE('Codigo do item: ' || CODIGO_ITEM);
    DBMS_OUTPUT.PUT_LINE('Nome do produto: ' || NOME_PRODUTO);
    DBMS_OUTPUT.PUT_LINE('Quantidade do item: ' || QTD_ITEM);
    
    IF SQL%NOTFOUND THEN
        RAISE_APPLICATION_ERROR(-20001, 'N o h  pedidos com este codigo.');
    END IF;

EXCEPTION
    WHEN ITEM_EXCEPTION THEN
        DBMS_OUTPUT.PUT_LINE(SQLERRM);
END;