-- EXERCICIO 2
CREATE OR REPLACE FUNCTION BuscarQuantidadeProdutoEmEstoque(CODIGO_ESTOQUE NUMBER, CODIGO_PRODUTO IN NUMBER)
RETURN NUMBER
IS
   QTD_ESTOQUE NUMBER := 0;
BEGIN

    SELECT E.QTD_PRODUTO
    INTO QTD_ESTOQUE
    FROM ESTOQUE_PRODUTO E
    WHERE E.COD_ESTOQUE = CODIGO_ESTOQUE
    AND E.COD_PRODUTO = CODIGO_PRODUTO;

    RETURN QTD_ESTOQUE;

END;