-- EXERCICIO 2: Crie uma procedure para inserir novos clientes, todos os valores deverão ser informados por parâmetros
-- e deverá ter tratamento de exceção
CREATE OR REPLACE PROCEDURE InserirCliente(
    CODIGO CLIENTE.COD_CLIENTE%TYPE,
    NOME CLIENTE.NOM_CLIENTE%TYPE,
    RAZAO_SOCIAL CLIENTE.DES_RAZAO_SOCIAL%TYPE,
    TIPO CLIENTE.TIP_PESSOA%TYPE,
    CPF_CNPJ CLIENTE.NUM_CPF_CNPJ%TYPE,
    CADASTRO CLIENTE.DAT_CADASTRO%TYPE,
    CANCELAMENTO CLIENTE.DAT_CANCELAMENTO%TYPE,
    STATUS CLIENTE.STA_ATIVO%TYPE    
)IS
    DML_ERRORS EXCEPTION;
    PRAGMA EXCEPTION_INIT(DML_ERRORS, -24381);
BEGIN
    INSERT INTO CLIENTE VALUES (CODIGO, NOME, RAZAO_SOCIAL, TIPO, CPF_CNPJ, CADASTRO, CANCELAMENTO, STATUS);
    COMMIT;
    EXCEPTION
        WHEN DML_ERRORS THEN
            DBMS_OUTPUT.PUT_LINE('Dados recebidos incorretamente');
            ROLLBACK;
END;