-- EXERCICIO 4: CRIE UMA PROCEDURE PARA DELETAR UM PEDIDO
CREATE OR REPLACE PROCEDURE DeletaPedido(
    CODIGO PEDIDO.COD_PEDIDO%TYPE
)IS
BEGIN
    DELETE FROM ITEM_PEDIDO WHERE COD_PEDIDO = CODIGO;
    DELETE FROM HISTORICO_PEDIDO WHERE COD_PEDIDO = CODIGO;
    DELETE FROM PEDIDO WHERE COD_PEDIDO = CODIGO;
    COMMIT;
END;